import type { Order } from "./types";

const CURRENT_STATUSES = new Set(["processing", "packed", "on_the_way"]);

export const mockOrders: Order[] = [
  {
    id: "73262",
    trackingNumber: "RK-73262",
    placedAt: "2026-08-17T13:45:00.000Z",
    status: "on_the_way",
    deliveryDate: "2026-08-20",
    rider: { name: "Kofi Boateng" },
    address: {
      name: "Ama Mensah",
      line: "14 Boundary Road, East Legon",
      city: "Accra",
      region: "Greater Accra",
    },
    shipping: 0,
    subtotal: 888,
    total: 888,
    lines: [
      {
        productId: "p-001",
        slug: "golden-basmati-rice",
        name: "Golden Basmati Rice",
        imageUrl: "/images/products/golden-basmati-rice-1.jpg",
        quantity: 1,
        unitPrice: 189,
        attributes: { Weight: "5kg" },
      },
      {
        productId: "p-004",
        slug: "extra-virgin-olive-oil",
        name: "Extra Virgin Olive Oil",
        imageUrl: "/images/products/extra-virgin-olive-oil-1.jpg",
        quantity: 2,
        unitPrice: 95,
        attributes: { Volume: "500ml" },
      },
      {
        productId: "p-010",
        slug: "velvet-musk-body-mist",
        name: "Velvet Musk Body Mist",
        imageUrl: "/images/products/velvet-musk-body-mist-1.jpg",
        quantity: 1,
        unitPrice: 89,
        attributes: { Volume: "200ml" },
      },
      {
        productId: "p-013",
        slug: "ivory-linen-wrap-dress",
        name: "Ivory Linen Wrap Dress",
        imageUrl: "/images/products/ivory-linen-wrap-dress-1.jpg",
        quantity: 1,
        unitPrice: 420,
        attributes: { Size: "M" },
      },
    ],
  },
  {
    id: "74018",
    trackingNumber: "RK-74018",
    placedAt: "2026-08-19T08:12:00.000Z",
    status: "on_the_way",
    deliveryDate: "2026-08-22",
    address: {
      name: "Kwame Boateng",
      line: "House 8, Ahodwo Roundabout",
      city: "Kumasi",
      region: "Ashanti",
    },
    shipping: 0,
    subtotal: 1035,
    total: 1035,
    lines: [
      {
        productId: "p-019",
        slug: "canvas-court-sneakers",
        name: "Canvas Court Sneakers",
        imageUrl: "/images/products/canvas-court-sneakers-1.jpg",
        quantity: 1,
        unitPrice: 890,
        attributes: { Color: "White", Size: "40" },
      },
      {
        productId: "p-011",
        slug: "saffron-cedar-attar-oil",
        name: "Saffron Cedar Attar Oil",
        imageUrl: "/images/products/saffron-cedar-attar-oil-1.jpg",
        quantity: 1,
        unitPrice: 145,
        attributes: { Volume: "12ml" },
      },
    ],
  },
  {
    id: "71891",
    trackingNumber: "RK-71891",
    placedAt: "2026-08-16T11:20:00.000Z",
    status: "packed",
    deliveryDate: "2026-08-19",
    address: {
      name: "Efua Darko",
      line: "Plot 22, Community 10",
      city: "Tema",
      region: "Greater Accra",
    },
    shipping: 0,
    subtotal: 543,
    total: 543,
    lines: [
      {
        productId: "p-018",
        slug: "structured-shoulder-bag",
        name: "Structured Shoulder Bag",
        imageUrl: "/images/products/structured-shoulder-bag-1.jpg",
        quantity: 1,
        unitPrice: 399,
        attributes: { Color: "Black" },
      },
      {
        productId: "p-009",
        slug: "evaporated-milk-six-pack",
        name: "Evaporated Milk Six Pack",
        imageUrl: "/images/products/evaporated-milk-six-pack-1.jpg",
        quantity: 2,
        unitPrice: 72,
        attributes: { Pack: "6 x 410g" },
      },
    ],
  },
  {
    id: "70112",
    trackingNumber: "RK-70112",
    placedAt: "2026-07-28T16:05:00.000Z",
    status: "delivered",
    deliveryDate: "2026-07-31",
    rider: { name: "Ama Serwaa" },
    address: {
      name: "Yaw Owusu",
      line: "12 Ridge Road, Cantonments",
      city: "Accra",
      region: "Greater Accra",
    },
    shipping: 0,
    subtotal: 325,
    total: 325,
    lines: [
      {
        productId: "p-024",
        slug: "woven-storage-basket",
        name: "Woven Storage Basket",
        imageUrl: "/images/products/woven-storage-basket-1.jpg",
        quantity: 1,
        unitPrice: 180,
        attributes: { Material: "Rattan" },
      },
      {
        productId: "p-025",
        slug: "ceramic-serving-bowl-set",
        name: "Ceramic Serving Bowl Set",
        imageUrl: "/images/products/ceramic-serving-bowl-set-1.jpg",
        quantity: 1,
        unitPrice: 145,
        attributes: { Set: "3 pieces" },
      },
    ],
  },
  {
    id: "68940",
    placedAt: "2026-07-12T09:40:00.000Z",
    status: "cancelled",
    deliveryDate: "2026-07-15",
    address: {
      name: "Ama Mensah",
      line: "14 Boundary Road, East Legon",
      city: "Accra",
      region: "Greater Accra",
    },
    shipping: 0,
    subtotal: 380,
    total: 380,
    lines: [
      {
        productId: "p-014",
        slug: "cotton-poplin-day-dress",
        name: "Cotton Poplin Day Dress",
        imageUrl: "/images/products/cotton-poplin-day-dress-1.jpg",
        quantity: 1,
        unitPrice: 380,
        attributes: { Size: "S" },
      },
    ],
  },
];

export function isCurrentOrder(order: Order): boolean {
  return CURRENT_STATUSES.has(order.status);
}

